import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sneakerfit layout",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body className="min-h-screen font-archivo-black">{children}</body>
    </html>
  );
}
