import type React from "react";
import type { Metadata } from "next";
import { StoreContextWrapper } from "./_context/StoreContextWrapper";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "sonner";
import { StoreSidebar } from "./_components/sidebar";
import { Header } from "./_components/header";

export const metadata: Metadata = {
  title: "Sneakerfit store",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function StoreLayout({ children }: Readonly<LayoutProps>) {
  return (
    <StoreContextWrapper>
      <SidebarProvider defaultOpen={false}>
        <StoreSidebar />

        <SidebarInset>
          <div className="h-full w-full bg-zinc-950 text-gray-300">
            <Header />

            {children}
          </div>
        </SidebarInset>

        <Toaster position="top-center" />
      </SidebarProvider>
    </StoreContextWrapper>
  );
}
